/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hgrgroup;
import Clases.*;
import java.util.List;
import java.util.ArrayList;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author uriel
 */
public class AgregarModificacion extends javax.swing.JFrame {

    private SharedData sharedData;
    private String cliente;
    /**
     * Creates new form AgregarUsuario
     */
    public AgregarModificacion(SharedData sharedData, String cliente) {
        initComponents();
        this.sharedData = sharedData;
        this.cliente = cliente;
        
        this.setSize(671, 490);
        txtFieldDescri.setLineWrap(true); // Habilita el ajuste de línea
        txtFieldDescri.setWrapStyleWord(true); // Ajusta las líneas en palabras completas
    }

    public SharedData getSharedData() {
        return sharedData;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label7 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        txtFieldNombre = new java.awt.TextField();
        txtFieldEstado = new java.awt.TextField();
        txtFieldInicio = new java.awt.TextField();
        txtFieldFin = new java.awt.TextField();
        btnRegresar = new javax.swing.JButton();
        botonAgg1 = new javax.swing.JButton();
        txtFieldAdicional = new java.awt.TextField();
        label11 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFieldDescri = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label2.setName("Nueva Modificación"); // NOI18N
        label2.setText("Nueva Modificación");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 51, 102));
        label1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Descripción");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 51, 102));
        label3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Nombre");

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(0, 51, 102));
        label7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Estado");

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setBackground(new java.awt.Color(0, 51, 102));
        label9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("Fecha Fin");

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(new java.awt.Color(0, 51, 102));
        label10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Fecha Inicio");

        txtFieldNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtFieldEstado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtFieldInicio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        txtFieldFin.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnRegresar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        botonAgg1.setBackground(new java.awt.Color(0, 51, 102));
        botonAgg1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        botonAgg1.setForeground(new java.awt.Color(255, 255, 255));
        botonAgg1.setText("Agregar");
        botonAgg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgg1ActionPerformed(evt);
            }
        });

        txtFieldAdicional.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setBackground(new java.awt.Color(0, 51, 102));
        label11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label11.setForeground(new java.awt.Color(255, 255, 255));
        label11.setText("Costo Adicional");

        txtFieldDescri.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldDescri.setColumns(20);
        txtFieldDescri.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFieldDescri.setForeground(new java.awt.Color(0, 0, 0));
        txtFieldDescri.setRows(5);
        jScrollPane1.setViewportView(txtFieldDescri);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonAgg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(txtFieldInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(txtFieldEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(txtFieldFin, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(txtFieldAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(botonAgg1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ModificacionesLandingPage modiPage = new ModificacionesLandingPage(getSharedData(), cliente);
        this.setVisible(false);
        modiPage.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void botonAgg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgg1ActionPerformed
        // TODO add your handling code here:
         try {
            if (txtFieldNombre.getText().isEmpty() || txtFieldEstado.getText().isEmpty() || txtFieldInicio.getText().isEmpty() || txtFieldFin.getText().isEmpty() || txtFieldDescri.getText().isEmpty() || txtFieldAdicional.getText().isEmpty()  ) {
                JOptionPane.showMessageDialog(null, "Llene todos los espacios del formulario", "Error",JOptionPane.ERROR_MESSAGE);
            }else{
                List<String> descripcion = new ArrayList<>();
                String nombre, estado, fechaInicio, fechaFin, descri;
                double costoAdicional;
                nombre = txtFieldNombre.getText();
                descri = txtFieldDescri.getText();
                for (char c : descri.toCharArray()) {
                    descripcion.add(String.valueOf(c));
                }
            
                estado = txtFieldEstado.getText();
                costoAdicional = Double.parseDouble(txtFieldAdicional.getText());
            

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                dateFormat.setLenient(false); // Desactiva el modo flexible para el análisis de fechas
            
                try {
                    // Verificar si los campos están vacíos
                
                    fechaInicio = txtFieldInicio.getText();
                    Date fechaEntrega = dateFormat.parse(fechaInicio);
                    LocalDate dateInicio = fechaEntrega.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    
                    fechaFin = txtFieldFin.getText();
                    Date fechaEntrega2 = dateFormat.parse(fechaFin);
                    LocalDate dateFin = fechaEntrega2.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                    
                    
                    Modificaciones modi = new Modificaciones(nombre, descripcion, estado, dateInicio, dateFin, costoAdicional);
                    JOptionPane.showMessageDialog(null, "La modificación se agregó exitosamente", "Modificación Agregada",JOptionPane.INFORMATION_MESSAGE);
                    for(int i = 0; i < sharedData.getCasas().size(); i++){
                        if(sharedData.getCasas().get(i).getNombreCliente().equals(cliente)){
                            sharedData.getCasas().get(i).getModificaciones().add(modi);
                        };
                    };
                    
                    
                    txtFieldNombre.setText("");
                    txtFieldDescri.setText("");
                    txtFieldEstado.setText("");
                    txtFieldFin.setText("");
                    txtFieldInicio.setText("");
                    txtFieldAdicional.setText("");
                    
                
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Ingrese el formato correcto de la fecha dd/mm/yy", "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores válidos en los campos", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAgg1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgg1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label7;
    private java.awt.Label label9;
    private java.awt.TextField txtFieldAdicional;
    private javax.swing.JTextArea txtFieldDescri;
    private java.awt.TextField txtFieldEstado;
    private java.awt.TextField txtFieldFin;
    private java.awt.TextField txtFieldInicio;
    private java.awt.TextField txtFieldNombre;
    // End of variables declaration//GEN-END:variables
}
