/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hgrgroup;
import Clases.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author Familia
 */
public class ModificacionesLandingPage extends javax.swing.JFrame {
    private SharedData shareData;
    private DefaultTableModel modelo;
    private String cliente;
    /**
     * Creates new form CasasLandingPage
     */
    public ModificacionesLandingPage(SharedData data, String nombreCliente) {
        initComponents();
        this.shareData = data;
        this.modelo = new DefaultTableModel();
        this.cliente = nombreCliente;
        transparencia(btnRegresar);
        this.setSize(1520, 480);
        
        
        //Columnas
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Estado");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Entrega");
        modelo.addColumn("Costo Adicional");
        
        TableCellRenderer customRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component component = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        
            // Establece el ancho y alto específico para la columna de "Descripción"
            if (column == getColumnIndex("Descripción")) {
                component.setPreferredSize(new Dimension(500, 500));
            }
        
            return component;
        }
        };

        
        mostrarModificaciones();
        
        jTablaCasas.setModel(modelo);// Asigna el renderizador personalizado a la columna de "Descripción"
        jTablaCasas.getColumnModel().getColumn(getColumnIndex("Descripción")).setCellRenderer(customRenderer);
        
        //Desactivar edición
        desactivarCeldas();
        
    }

    public SharedData getSharedData() {
        return shareData;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaCasas = new javax.swing.JTable();
        label2 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jPanelRegresar = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabelRegresar = new javax.swing.JLabel();
        txtFieldBuscar = new java.awt.TextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTablaCasas.setBackground(new java.awt.Color(255, 255, 255));
        jTablaCasas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTablaCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Código Casa", "Fax", "Costo", "Modificaciones ", "Fecha Entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaCasas);
        if (jTablaCasas.getColumnModel().getColumnCount() > 0) {
            jTablaCasas.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 1360, 260));

        label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("MENÚ");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 20));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("CASAS");
        jPanel4.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        jPanelRegresar.setBackground(new java.awt.Color(0, 51, 102));

        btnRegresar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabelRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRegresarLayout = new javax.swing.GroupLayout(jPanelRegresar);
        jPanelRegresar.setLayout(jPanelRegresarLayout);
        jPanelRegresarLayout.setHorizontalGroup(
            jPanelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRegresar)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRegresarLayout.setVerticalGroup(
            jPanelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegresarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelRegresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 460));

        txtFieldBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel1.add(txtFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 126, 250, 23));

        btnBuscar.setBackground(new java.awt.Color(0, 51, 102));
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 126, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(0, 51, 102));
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 81, 31));

        btnModificar.setBackground(new java.awt.Color(0, 51, 102));
        btnModificar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 32));

        btnEliminar.setBackground(new java.awt.Color(0, 51, 102));
        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 81, 32));

        btnMostrar.setBackground(new java.awt.Color(0, 51, 102));
        btnMostrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("Mostrar Todo");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 85, -1, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int getColumnIndex(String columnName) {
        return jTablaCasas.getColumnModel().getColumnIndex(columnName);
    }
    
    private void transparencia(JButton btn){
        btn.setOpaque(false);
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
    };
    
    private void desactivarCeldas(){
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            Class<?> colClass = modelo.getColumnClass(i); //Toma el tipo de dato que tiene una columna, por eso el genérico
            this.jTablaCasas.setDefaultEditor(colClass, null); // Esto deshabilita la edición
        }
    };
     
    private void mostrarModificaciones(){   
        modelo.setRowCount(0);
        for(int i = 0; i < shareData.getCasas().size(); i++){
            if(shareData.getCasas().get(i).getNombreCliente().equals(cliente)){
                for(int k = 0; k < shareData.getCasas().get(i).getModificaciones().size(); k++){
                     List<String> descripciones = new ArrayList<>(); // Lista para almacenar descripciones

                    List<Modificaciones> modificaciones = shareData.getCasas().get(i).getModificaciones();
                    for (Modificaciones modificacion : modificaciones) {
                        List<String> descripcionesModificacion = modificacion.getDescrip();
                        descripciones.addAll(descripcionesModificacion);
                    }

                    // Convierte la lista de descripciones en una sola cadena, si es necesario
                    String descripcionesConcatenadas = String.join(", ", descripciones);
                    String [] row = new String[7];
                    row[0] = shareData.getCasas().get(i).getModificaciones().get(i).getNombreModi();
                    row[1] = descripcionesConcatenadas;
                    row[2] = shareData.getCasas().get(i).getModificaciones().get(i).getEstado();
                    row[3] = shareData.getCasas().get(i).getModificaciones().get(i).getNumCasa();
                    row[4] = String.valueOf(shareData.getCasas().get(i).getModificaciones().get(i).getFechaInicio());
                    row[5] = String.valueOf(shareData.getCasas().get(i).getModificaciones().get(i).getFechaFin());
                    row[6] = String.valueOf(shareData.getCasas().get(i).getModificaciones().get(i).getCostoAdicional());
                    modelo.addRow(row);
                    
                }
            };
        }
    } 
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        // Supongamos que txtFieldBuscar.getText() contiene el texto a buscar.
        String textoBuscado = txtFieldBuscar.getText();
        modelo.setRowCount(0); // Limpia el modelo antes de agregar nuevos resultados.

        for (Casas casa : shareData.getCasas()) {
            for (Modificaciones modificacion : casa.getModificaciones()) {
                if (modificacion.getNombreModi().equals(textoBuscado)) {
                    String[] row = new String[10];
                    row[0] = casa.getNombreCliente();
                    row[1] = casa.getCodigo();
                    row[2] = casa.getFaseConstru();
                    row[3] = String.valueOf(casa.getCostoBase());
                    row[4] = String.valueOf(casa.getCostoModificaciones());
                    row[5] = String.valueOf(casa.getModificaciones().size());
                    row[6] = String.valueOf(casa.getCostoAdons());
                    row[7] = String.valueOf(casa.getAdons().size());
                    row[8] = String.valueOf(casa.getCostoFinal());
                    row[9] = String.valueOf(casa.getFechaEntrega());
                    modelo.addRow(row);
                    encontrado = true;
                }
            }
        }
        
        if(encontrado != true){
            JOptionPane.showMessageDialog(null, "Modificación Inexistente", "Error",JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AgregarCasa pagAgregar = new AgregarCasa(getSharedData());
        this.setVisible(false);
        pagAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        Color colorRgb= new Color(0, 102, 204);
        jPanelRegresar.setBackground(colorRgb);
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(getSharedData());
        this.setVisible(false);
        menu.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        Color colorRgb= new Color(0,51,102);
        jPanelRegresar.setBackground(colorRgb);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int fila = jTablaCasas.getSelectedRow();
        try{
            Object valor = jTablaCasas.getValueAt(fila,0);
            ModificarCasa modiPage = new ModificarCasa(getSharedData(), (String) valor); //Convierto valor a String
            modiPage.setVisible(true);
            this.setVisible(false);
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Seleccione una fila para modificar", "Error",JOptionPane.ERROR_MESSAGE);
        };
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = jTablaCasas.getSelectedRow();
        if(fila >= 0){
            modelo.removeRow(fila);
            shareData.getCasas().remove(fila);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila para eliminar", "Error",JOptionPane.ERROR_MESSAGE);
        };
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        mostrarModificaciones();
    }//GEN-LAST:event_btnMostrarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaCasas;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField txtFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
