/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hgrgroup;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Clases.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uriel
 */
public class UsuariosLandingPage extends javax.swing.JFrame {
    private SharedData shareData;
    DefaultTableModel modelo;
    /**
     * Creates new form UsuariosLandingPage
     */
    public UsuariosLandingPage(SharedData shareData) {
        initComponents();
        
        //Inicio de atributos
        this.modelo = new DefaultTableModel();
        this.shareData = shareData;
        
        //Métodos relevantes
        this.setSize(1520, 480);
        
        transparencia(btnRegresar);
        
        //Información Tabla
        modelo.addColumn("Usuario");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Nombre");
        modelo.addColumn("DPI");
        modelo.addColumn("Edad");
        modelo.addColumn("Cargo");
        modelo.addColumn("Departamento");
        modelo.addColumn("Email");
        mostrarUsuarios();
        this.jTablaUsuarios.setModel(modelo);
        
        //Desactivamos celdas
        desactivarCeldas();
        
        txtFieldBuscar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscar(txtFieldBuscar.getText()); // Llama a la función buscar con el texto ingresado
            }
        });
    }

    public SharedData getShareData() {
        return shareData;
    }
    
     private void transparencia(JButton btn){
        btn.setOpaque(false);
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(false);
    };
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDinamico = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jPanelRegresar = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabelRegresar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtFieldBuscar = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDinamico.setBackground(new java.awt.Color(255, 255, 255));
        panelDinamico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("USUARIOS");
        jPanel3.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        label2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("MENÚ");
        jPanel3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jPanelRegresar.setBackground(new java.awt.Color(0, 51, 102));

        btnRegresar.setBackground(new java.awt.Color(0, 51, 102));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabelRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N

        javax.swing.GroupLayout jPanelRegresarLayout = new javax.swing.GroupLayout(jPanelRegresar);
        jPanelRegresar.setLayout(jPanelRegresarLayout);
        jPanelRegresarLayout.setHorizontalGroup(
            jPanelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelRegresarLayout.setVerticalGroup(
            jPanelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelRegresarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPanel3.add(jPanelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 70));

        panelDinamico.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 450));

        btnAgregar.setBackground(new java.awt.Color(0, 51, 102));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelDinamico.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 81, 31));

        btnModificar.setBackground(new java.awt.Color(0, 51, 102));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelDinamico.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 80, 32));

        btnEliminar.setBackground(new java.awt.Color(0, 51, 102));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelDinamico.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 81, 32));
        panelDinamico.add(txtFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 250, 23));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTablaUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        jTablaUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        jTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña", "Nombre", "DPI", "Edad", "Cargo", "Teléfono", "Departamento", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaUsuarios.setFocusable(false);
        jTablaUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablaUsuarios);
        if (jTablaUsuarios.getColumnModel().getColumnCount() > 0) {
            jTablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTablaUsuarios.getColumnModel().getColumn(2).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTablaUsuarios.getColumnModel().getColumn(3).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTablaUsuarios.getColumnModel().getColumn(4).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(4).setPreferredWidth(35);
            jTablaUsuarios.getColumnModel().getColumn(5).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(6).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(7).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTablaUsuarios.getColumnModel().getColumn(8).setResizable(false);
            jTablaUsuarios.getColumnModel().getColumn(8).setPreferredWidth(200);
        }

        panelDinamico.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 1360, 190));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar Usuario");
        panelDinamico.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        getContentPane().add(panelDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void buscar(String textoIngresado) {
        boolean encontrado = false;
        List<Usuarios> usuariosEncontrados = new ArrayList<>();

        for (Usuarios usuario : shareData.getUsuarios()) {
            if (textoIngresado.isEmpty()) {
                mostrarUsuarios();
                return; // No es necesario seguir buscando si el campo de búsqueda está vacío
            } else if (textoIngresado.equals(usuario.getUsuario()) || textoIngresado.equals(usuario.getNombreUsuario()) || textoIngresado.equals(String.valueOf(usuario.getDpi())) || textoIngresado.equals(String.valueOf(usuario.getEdad())) || textoIngresado.equals(usuario.getCargo()) || textoIngresado.equals(usuario.getDepartamento()) || textoIngresado.equals(usuario.getEmail())) {
                usuariosEncontrados.add(usuario);
                encontrado = true;
            }
        }

        if (encontrado) {
            modelo.setRowCount(0);
            for (Usuarios usuarioEncontrado : usuariosEncontrados) {
                String[] row = new String[8];
                row[0] = usuarioEncontrado.getUsuario();
                row[1] = usuarioEncontrado.getContrasenaOfuscada();
                row[2] = usuarioEncontrado.getNombreUsuario();
                row[3] = String.valueOf(usuarioEncontrado.getDpi());
                row[4] = String.valueOf(usuarioEncontrado.getEdad());
                row[5] = String.valueOf(usuarioEncontrado.getTelefono());
                row[6] = usuarioEncontrado.getDepartamento();
                row[7] = usuarioEncontrado.getEmail();
                modelo.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AgregarUser agUser = new AgregarUser(getShareData());
        this.setVisible(false);
        agUser.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        int fila = jTablaUsuarios.getSelectedRow();
        try{
            Object valor = jTablaUsuarios.getValueAt(fila,0);
            ModificarUserr modiPage = new ModificarUserr(getShareData(), (String) valor); //Convierto valor a String
            modiPage.setVisible(true);
            this.setVisible(false);
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Seleccione una fila para modificar", "Error",JOptionPane.ERROR_MESSAGE);
        };
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = jTablaUsuarios.getSelectedRow();
        if(fila > 0){
            modelo.removeRow(fila);
            shareData.getUsuarios().remove(fila);
        }else if(fila == 0){
            JOptionPane.showMessageDialog(null, "El usuario administrador no se puede eliminar", "Error",JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "El usuario administrador no se puede eliminar", "Error",JOptionPane.ERROR_MESSAGE);
        };
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(getShareData());
        this.setVisible(false);
        menu.setVisible(true);

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        Color colorRgb= new Color(0,51,102);
        jPanelRegresar.setBackground(colorRgb);
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        Color colorRgb= new Color(0, 102, 204);
        jPanelRegresar.setBackground(colorRgb);
    }//GEN-LAST:event_btnRegresarMouseEntered
   
    
    private void mostrarUsuarios(){   
        modelo.setRowCount(0);
        for(int i = 0; i < shareData.getUsuarios().size(); i++){
            String [] row = new String[8];
            row[0] = shareData.getUsuarios().get(i).getUsuario();
            row[1] = shareData.getUsuarios().get(i).getContrasenaOfuscada();
            row[2] = shareData.getUsuarios().get(i).getNombreUsuario();
            row[3] = String.valueOf(shareData.getUsuarios().get(i).getDpi());
            row[4] = String.valueOf(shareData.getUsuarios().get(i).getEdad());
            row[5] = String.valueOf(shareData.getUsuarios().get(i).getTelefono());
            row[6] = shareData.getUsuarios().get(i).getDepartamento();
            row[7] = shareData.getUsuarios().get(i).getEmail();
            modelo.addRow(row);
        };
    } 
    
    public void desactivarCeldas(){
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            Class<?> colClass = modelo.getColumnClass(i); //Toma el tipo de dato que tiene una columna, por eso el genérico
            this.jTablaUsuarios.setDefaultEditor(colClass, null); // Esto deshabilita la edición
        }
    };
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaUsuarios;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JPanel panelDinamico;
    private java.awt.TextField txtFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
